### ISSUE TITLE
It will be great to add some other useful logic operators

### ISSUE THREAD

**Issue by hanhiver** [Gusabary/FlowChar#5]
I think the following logic may very useful: 
1. switch or multiple elseif. 
2. break and continue in the loop.

**Comment by Gusabary** [comment]
Of course you're right. Without these keywords the pseudo-code might get kind of verbose if you want to express more complicated logic. But now the pseudo-code itself is actually self-contained or complete since it has supported sequential, branch and loop structure.

Anyway, supporting more keywords is not a piece of cake. It might be considered in following versions.

Thanks for your attention and support!
